apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  releaseName: choerodon/minio
  targetNamespace: web-host-devel
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://openchart.choerodon.com.cn/choerodon/c7n
    name: miniov4
    version: 7.0.2
  values:
    replicas: 4
    image:
      tag: latest
    accessKey: AKIAVJDUW7HRSB7IQXAF
    secretKey: Lifeovereverything$971

    service:
      type: LoadBalancer
    defaultBucket:
      enabled: false
      name: velero ## permet la création du bucket de sauvegarde à l’installation
    persistence:
      enabled: true ## activation de la persistance du volume
      accessMode: ReadWriteOnce
      size: 50Gi ## on définit la taille de notre PV dédié à Minio

    s3gateway:
      enabled: true
      accessKey: AKIAVJDUW7HRSB7IQXAF
      secretKey: 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

    ## Update strategy for Deployments
    DeploymentUpdate:
      type: RollingUpdate
      maxUnavailable: 0
      maxSurge: 100%

    ## Update strategy for StatefulSets
    StatefulSetUpdate:
      updateStrategy: RollingUpdate

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - images.webiconographie.com ## On définit une URL d'accès pour la webui Minio à travers notre ingress pour exposer le service minio