apiVersion: v1
description: High Performance, Kubernetes Native Object Storage
name: minio
version: 7.0.2
appVersion: master
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
dependencies:
- name: postgresql
  version: 9.2.1
  repository: https://charts.bitnami.com/bitnami