image:
  repository: minio/minio 
  tag: latest 
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 2G
mode: distributed
accessKey: AKIAVJDUW7HRSB7IQXAF
secretKey: Lifeovereverything$971


service:
  type: NodePort 
defaultBucket:
  enabled: false
  name: velero ## permet la création du bucket de sauvegarde à l’installation
persistence:
  enabled: true ## activation de la persistance du volume
  accessMode: ReadWriteOnce
  #storageClass: ""
  #VolumeName: ""
  size: 50Gi ## on définit la taille de notre PV dédié à Minio


## Update strategy for Deployments
DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

## Update strategy for StatefulSets
StatefulSetUpdate:
  updateStrategy: RollingUpdate

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - images.webiconographie.com ## On définit une URL d'accès pour la webui Minio à travers notre ingress pour exposer le service minio